name: Deploy Nuxt to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUXT_APP_BASE_URL: /taller-breddy/
      NUXT_PUBLIC_SITE_URL: https://fmonroy75.github.io/taller-breddy/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Generate Nuxt site
        run: npx nuxt build --preset github_pages

      - name: Verify generated files
        run: |
          echo "Contenido de .output/public:"
          find .output/public -maxdepth 2 -type f | sort

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          name: github-pages
          path: ./.output/public

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
